synonym_replace_templates = [
    'a picture of a {}.',
    'a snapshot of a {}.',
    'a photograph of a {}.',
    'a shot of a {}.',
    'an image of a {}.',
    'a portrait of a {}.',
    'a still of a {}.',
    'a visual of a {}.',
    'a scene of a {}.',
    'a depiction of a {}.',
    'a representation of a {}.',
    'a capture of a {}.',
    'a recording of a {}.',
    'a scene image of a {}.',
    'a visual capture of a {}.',
    'a document of a {}.',
    'a composition of a {}.',
    'a film of a {}.',
    'a display of a {}.',
    'a print of a {}.',
    'a digital image of a {}.',
    'a visual shot of a {}.',
    'a digital shot of a {}.',
    'a moment of {}.',
    'a time-lapse image of a {}.',
    'an action shot of a {}.',
    'a candid shot of a {}.',
    'a spontaneous shot of a {}.',
    'a spontaneous image of a {}.',
    'an outdoor image of a {}.',
    'a natural shot of a {}.',
    'a cinematic shot of a {}.',
    'a captured moment of a {}.',
    'a natural light image of a {}.',
    'a close-up shot of a {}.',
    'a candid moment of a {}.',
    'a professional image of a {}.',
    'a snapshot moment of a {}.',
    'a vintage photograph of a {}.',
    'an artistic shot of a {}.',
    'a clear shot of a {}.',
    'a high-quality image of a {}.',
    'a sharp image of a {}.',
    'a landscape shot of a {}.',
    'an abstract image of a {}.',
    'a low-res shot of a {}.',
    'a black-and-white picture of a {}.',
    'a colorful picture of a {}.',
    'a zoomed-in shot of a {}.',
    'a macro shot of a {}.',
    'a large-scale shot of a {}.',
    'a small-scale image of a {}.',
    'a sharp-focused visual of a {}.',
    'a high-res shot of a {}.',
    'a framed shot of a {}.',
    'a surreal shot of a {}.',
    'a staged image of a {}.',
    'a profile shot of a {}.',
    'a front view image of a {}.',
    'an overhead shot of a {}.',
    'a family portrait of a {}.',
    'an angled image of a {}.',
    'a daytime picture of a {}.',
    'a wide-angle shot of a {}.',
    'a natural image of a {}.',
    'a long-exposure shot of a {}.',
    'a documentary shot of a {}.',
    'a clear background shot of a {}.',
    'a blurred background image of a {}.',
    'a minimalistic shot of a {}.',
    'a portrait-style image of a {}.',
    'a picture of {}.',
    'a photograph of {}.',
    'a snapshot of {}.',
    'a shot of {}.',
    'a still of {}.',
    'a portrait of {}.',
    'a visual of {}.',
    'a depiction of {}.',
    'a representation of {}.',
    'a rendering of {}.',
    'a capture of {}.',
    'a scene of {}.',
    'a view of {}.',
    'a display of {}.',
    'a presentation of {}.',
    'a composition of {}.',
    'a film of {}.',
    'a document of {}.',
    'a print of {}.',
    'a image of {}.',
    'a visual portrayal of {}.',
    'a frame capture of {}.',
    'a pictorial representation of {}.',
    'a scenic image of {}.',
    'a time-lapse image of {}.',
    'a candid moment of {}.',
    'a spontaneous picture of {}.',
    'a moment captured of {}.',
    'a fleeting shot of {}.',
    'a lively image of {}.',
    'a outdoor portrait of {}.',
    'a sharp image of {}.',
    'a close-up shot of {}.',
    'a zoomed-in picture of {}.',
    'a focused shot of {}.',
    'a striking photo of {}.',
    'a composed frame of {}.',
    'a natural image of {}.',
    'a rare capture of {}.',
    'a stunning shot of {}.',
    'a vivid image of {}.',
    'a crystal-clear shot of {}.',
    'a memorable picture of {}.',
    'a professional photograph of {}.',
    'a framed composition of {}.',
    'a crisp shot of {}.',
    'a unique angle of {}.',
    'a dynamic frame of {}.',
    'a wide-angle shot of {}.',
    'a well-lit photograph of {}.',
    'a minimalist shot of {}.',
    'a black-and-white shot of {}.',
    'a colorful photograph of {}.',
    'a beautiful shot of {}.',
    'a dramatic portrayal of {}.',
    'a vintage photo of {}.',
    'a timeless snapshot of {}.',
    'a stylized shot of {}.',
    'a creative photo of {}.',
    'a close-up view of {}.',
    'a high-definition shot of {}.',
    'a documentary photo of {}.',
    'a candid photo of {}.',
    'a rare moment captured of {}.',
    'a striking portrait of {}.',
    'a family snapshot of {}.',
    'a quick capture of {}.',
    'a candid frame of {}.',
    'a spectacular image of {}.',
    'a panoramic picture of {}.',
    'a sharp-focus frame of {}.',
    'a natural light photo of {}.',
    'a cinematic frame of {}.',
    'a dramatic shot of {}.',
    'a moment captured of {}.',
    'a professional shot of {}.',
    'a striking visual of {}.',
    'a focused snapshot of {}.',
    'a vivid photo of {}.',
    'a sharp photo of {}.',
    'a pure shot of {}.',
    'a frame composition of {}.',
    'a clear-cut photograph of {}.',
    'a documentary picture of {}.'
]

word_order_templates = [
    'a photo of a {}, something special.',
    'a photo of a {}, something memorable.',
    'a photo of a {}, something unique.',
    'a photo of a {}, something beautiful.',
    'a photo of a {}, something remarkable.',
    'a photo of a {}, something I cherish.',
    'a photo of a {}, something vivid.',
    'a photo of a {}, something fun.',
    'a photo of a {}, something charming.',
    'a photo of a {}, something delightful.',
    'a photo of a {}, something I captured.',
    'a photo of a {}, something inspiring.',
    'a photo of a {}, something lovely.',
    'a photo of a {}, something stunning.',
    'a photo of a {}, something breathtaking.',
    'a photo of a {}, something nostalgic.',
    'a photo of a {}, something candid.',
    'a photo of a {}, something amazing.',
    'a photo of a {}, something artistic.',
    'a photo of a {}, something peaceful.',
    'a photo of a {}, something magical.',
    'a photo of a {}, something timeless.',
    'a photo of a {}, something classic.',
    'a photo of a {}, something splendid.',
    'a photo of a {}, something wonderful.',
    'a photo of a {}, something delightful to see.',
    'a photo of a {}, something worth sharing.',
    'a photo of a {}, something unforgettable.',
    'a photo of a {}, something truly special.',
    'a photo of a {}, something I treasure.',
    'a photo of a {}, something I admire.',
    'a photo of a {}, something I enjoyed capturing.',
    'a photo of a {}, something simple and elegant.',
    'a photo of a {}, something full of life.',
    'a photo of a {}, something extraordinary.',
    'a photo of a {}, something calming.',
    'a photo of a {}, something full of charm.',
    'a photo of a {}, something vibrant.',
    'a photo of a {}, something that caught my eye.',
    'a photo of a {}, something that feels alive.',
    'a photo of a {}, something captured in a moment.',
    'a photo of a {}, something that makes me smile.',
    'a photo of a {}, something that stands out.',
    'a photo of a {}, something I couldn’t miss.',
    'a photo of a {}, something lovely to look at.',
    'a photo of a {}, something that’s simply great.',
    'a photo of a {}, something that brings joy.',
    'a photo of a {}, something delightful to remember.',
    'a photo of a {}, something that looks perfect.',
    'a photo of a {}, something pure and simple.',
    'a photo of a {}, something refreshingly beautiful.',
    'a photo of a {}, something vibrant and clear.',
    'a photo of a {}, something natural and fresh.',
    'a photo of a {}, something bright and cheerful.',
    'a photo of a {}, something gentle and soft.',
    'a photo of a {}, something rare and special.',
    'a photo of a {}, something clear and vivid.',
    'a photo of a {}, something extraordinary to see.',
    'a photo of a {}, something that makes me proud.',
    'a photo of a {}, something that tells a story.',
    'a photo of a {}, something spontaneous and lively.',
    'a photo of a {}, something with a unique charm.',
    'a photo of a {}, something full of grace.',
    'a photo of a {}, something that feels timeless.',
    'a photo of a {}, something I couldn’t forget.',
    'a photo of a {}, something that captures the moment.',
    'a photo of a {}, something full of energy.',
    'a photo of a {}, something warm and inviting.',
    'a photo of a {}, something soft and pleasing.',
    'a photo of a {}, something truly inspiring.',
    'a photo of a {}, something I’m glad to share.',
    'a photo of a {}, something precious and rare.',
    'a photo of a {}, something captivating.',
    'a photo of a {}, something graceful and elegant.',
    'a photo of a {}, something lively and fresh.',
    'a photo of a {}, something that feels just right.',
    'a photo of a {}, something peaceful and quiet.',
    'a photo of a {}, something cheerful and bright.',
    'a photo of a {}, something vibrant and alive.',
    'a photo of a {}, something I love to look at.',
    'a photo of a {}, something wonderfully unique.',
    'a photo of a {}, something refreshing.',
    'a photo of a {}, something filled with charm.',
    'a photo of a {}, something unforgettable and vivid.',
    'a photo of a {}, something delightful to keep.',
    'a photo of a {}, something worth capturing.',
]

emotional_templates = [
    'a stunning photo of {}.',
    'a heartwarming photo of {}.',
    'an incredibly beautiful shot of {}.', 
    'a charming photo of {}.',
    'a delightful shot of {}.',
    'a breathtaking photo of {}.',
    'a gorgeous shot of {}.',
    'an adorable photo of {}.',
    'a peaceful image of {}.',
    'a magical photo of {}.',
    'a moving shot of {}.',
    'an inspiring photo of {}.',
    'a sweet shot of {}.',
    'a lovely image of {}.',
    'an uplifting photo of {}.', 
    'a vibrant shot of {}.',
    'an enchanting photo of {}.',
    'a soulful shot of {}.',
    'a memorable image of {}.',
    'a striking photo of {}.',
    'an evocative image of {}.',
    'a powerful photo of {}.',
    'a heart-touching photo of {}.',
    'an emotional shot of {}.',
    'a magical snapshot of {}.',
    'a fantastic photo of {}.',
    'a wonderful image of {}.',
    'a tender photo of {}.',
    'a whimsical image of {}.',
    'a striking shot of {}.',
    'a captivating photo of {}.',
    'an artistic image of {}.',
    'a nostalgic photo of {}.',
    'a delightful snapshot of {}.',
    'an extraordinary photo of {}.',
    'a glorious image of {}.',
    'an awe-inspiring photo of {}.',
    'a splendid photo of {}.',
    'a remarkable image of {}.',
    'a sweet memory of {}.',
    'a poignant photo of {}.',
    'a dramatic image of {}.',
    'an emotional photo of {}.',
    'a mesmerizing photo of {}.',
    'a pure shot of {}.',
    'a touching photo of {}.',
    'an uplifting moment of {}.',
    'a peaceful capture of {}.',
    'a sorrowful image of {}.',
    'a tender moment of {}.',
    'a regretful image of {}.',
    'a broken image of {}.',
    'a mournful shot of {}.',
    'a heartwarming moment of {}.',
    'a soul-crushing photo of {}.',
    'a gloomy image of {}.',
    'a hauntingly empty photo of {}.',
    'an overwhelming photo of {}.',
    'a hopeless photo of {}.',
    'a depressing shot of {}.',
    'a disconnected image of {}.',
    'an unsettling photo of {}.',
    'a hollow photo of {}.',
    'a cold and lifeless image of {}.',
    'a tragic photo of {}.',
    'a sad photo of {}.',
    'a lonely shot of {}.',
    'a despairing shot of {}.',
    'an eerie photo of {}.',
    'a gray photo of {}.',
    'a disheartening photo of {}.',
    'a sorrowful image of {}.'
]

tense_variation_templates = [
    'I am taking a photo of a {}.', 
    'I have taken a photo of a {}.', 
    'I had taken a photo of a {}.', 
    'I will have taken a photo of a {}.', 
    'She is taking a photo of a {}.', 
    'She will take a photo of a {}.', 
    'She has taken a photo of a {}.', 
    'She had taken a photo of a {}.', 
    'They are taking a photo of a {}.', 
    'They will take a photo of a {}.', 
    'They have taken a photo of a {}.', 
    'They had taken a photo of a {}.', 
    'We are taking a photo of a {}.', 
    'We will take a photo of a {}.', 
    'We have taken a photo of a {}.', 
    'We had taken a photo of a {}.', 
    'You are taking a photo of a {}.', 
    'You will take a photo of a {}.', 
    'You have taken a photo of a {}.', 
    'You had taken a photo of a {}.', 
    'She took a photo of a {}.', 
    'They took a photo of a {}.', 
    'We took a photo of a {}.', 
    'You took a photo of a {}.'
]

detailed_description_templates = [
    'a well-lit photo of a {}.', 
    'a poorly lit photo of a {}.', 
    'a close-up photo of a {}.', 
    'a wide-angle photo of a {}.',
    'a blurry photo of a {}.',
    'a crisp photo of a {}.', 
    'a detailed photo of a {}.', 
    'a shaky photo of a {}.',
    'an overexposed photo of a {}.', 
    'an underexposed photo of a {}.', 
    'a high-quality photo of a {}.', 
    'a low-quality photo of a {}.',
    'a faded photo of a {}.', 
    'a vibrant photo of a {}.', 
    'a colorful photo of a {}.', 
    'a black-and-white photo of a {}.',
    'a sepia-toned photo of a {}.', 
    'a vintage-style photo of a {}.', 
    'a modern photo of a {}.', 
    'a classic photo of a {}.',
    'a snapshot of a {}.', 
    'an action-packed photo of a {}.', 
    'a still photo of a {}.', 
    'a candid photo of a {}.',
    'a posed photo of a {}.', 
    'an amateur photo of a {}.', 
    'a panoramic photo of a {}.', 
    'a time-lapse photo of a {}.',
    'a sunset photo of a {}.', 
    'a sunrise photo of a {}.', 
    'a nature-focused photo of a {}.', 
    'a cityscape photo of a {}.',
    'a landscape photo of a {}.', 
    'a night-time photo of a {}.', 
    'a daytime photo of a {}.', 
    'an abstract photo of a {}.',
    'a sharp-focused photo of a {}.', 
    'a soft-focused photo of a {}.', 
    'a macro photo of a {}.', 
    'a drone photo of a {}.',
    'a 360-degree photo of a {}.', 
    'a zoomed-in photo of a {}.', 
    'a zoomed-out photo of a {}.', 
    'a symmetrical photo of a {}.',
    'an asymmetrical photo of a {}.', 
    'a glowing photo of a {}.', 
    'a dim photo of a {}.', 
    'a vibrant-colored photo of a {}.',
    'a monochrome photo of a {}.', 
    'a close-up shot of a {}.', 
    'a well-composed photo of a {}.', 
    'a poorly composed photo of a {}.',
    'a perfectly framed photo of a {}.', 
    'a skewed photo of a {}.', 
    'a detailed close-up photo of a {}.', 
    'a creative photo of a {}.',
    'a chaotic photo of a {}.', 
    'a minimalist photo of a {}.', 
    'a dramatic photo of a {}.', 
    'a peaceful photo of a {}.',
    'a lively photo of a {}.', 
    'a muted photo of a {}.', 
    'a colorful shot of a {}.', 
    'a fresh photo of a {}.',
    'a vibrant photo of a {}.', 
    'a vintage-inspired photo of a {}.', 
    'a modern-day photo of a {}.', 
    'a bright photo of a {}.',
    'a dull photo of a {}.', 
    'an eye-catching photo of a {}.', 
    'a motion-blurred photo of a {}.', 
    'a perfectly sharp photo of a {}.',
    'a high-angle photo of a {}.', 
    'a low-angle photo of a {}.', 
    'a candid moment photo of a {}.', 
    'a momentous photo of a {}.',
    'a well-lit portrait of a {}.', 
    'a poorly lit portrait of a {}.', 
    'a finely detailed photo of a {}.', 
    'a distorted photo of a {}.',
    'a sharp-edged photo of a {}.', 
    'a soft-edged photo of a {}.', 
    'a perfect shot of a {}.', 
    'a messy photo of a {}.',
    'a crystal-clear photo of a {}.', 
    'an overexposed shot of a {}.', 
    'a blurred background photo of a {}.', 
    'a clear background photo of a {}.',
    'a dark-toned photo of a {}.', 
    'a soft-focus photo of a {}.', 
    'a well-lit indoor photo of a {}.', 
    'a shadowy indoor photo of a {}.',
    'a quiet photo of a {}.', 
    'a bustling photo of a {}.', 
    'a chaotic urban photo of a {}.',
    'a vintage photograph of a {}.', 
    'a professional shot of a {}.', 
    'an artistic shot of a {}.', 
    'a striking photo of a {}.',
    'a well-lit photo of the {}.', 
    'a poorly lit photo of the {}.', 
    'a close-up photo of the {}.', 
    'a wide-angle photo of the {}.',
    'a blurry photo of the {}.', 
    'a crisp photo of the {}.', 
    'a detailed photo of the {}.', 
    'a shaky photo of the {}.',
    'a overexposed photo of the {}.', 
    'a underexposed photo of the {}.', 
    'a high-quality photo of the {}.', 
    'a low-quality photo of the {}.',
    'a faded photo of the {}.', 
    'a vibrant photo of the {}.', 
    'a colorful photo of the {}.', 
    'a black-and-white photo of the {}.',
    'a sepia-toned photo of the {}.', 
    'a vintage-style photo of the {}.', 
    'a modern photo of the {}.', 
    'a classic photo of the {}.',
    'a snapshot of the {}.', 
    'a action-packed photo of the {}.', 
    'a still photo of the {}.', 
    'a candid photo of the {}.',
    'a posed photo of the {}.', 
    'a professional photo of the {}.', 
    'a panoramic photo of the {}.', 
    'a time-lapse photo of the {}.',
    'a sunset photo of the {}.', 
    'a sunrise photo of the {}.', 
    'a nature-focused photo of the {}.', 
    'a cityscape photo of the {}.',
    'a landscape photo of the {}.', 
    'a night-time photo of the {}.', 
    'a daytime photo of the {}.', 
    'a abstract photo of the {}.',
    'a sharp-focused photo of the {}.', 
    'a soft-focused photo of the {}.', 
    'a macro photo of the {}.', 
    'a drone photo of the {}.',
    'a 360-degree photo of the {}.', 
    'a zoomed-in photo of the {}.', 
    'a zoomed-out photo of the {}.', 
    'a symmetrical photo of the {}.',
    'a asymmetrical photo of the {}.', 
    'a glowing photo of the {}.', 
    'a dim photo of the {}.', 
    'a vibrant-colored photo of the {}.',
    'a monochrome photo of the {}.', 
    'a close-up shot of the {}.', 
    'a well-composed photo of the {}.', 
    'a poorly composed photo of the {}.',
    'a perfectly framed photo of the {}.', 
    'a skewed photo of the {}.', 
    'a detailed close-up photo of the {}.', 
    'a creative photo of the {}.',
    'a chaotic photo of the {}.', 
    'a minimalist photo of the {}.', 
    'a dramatic photo of the {}.', 
    'a peaceful photo of the {}.',
    'a lively photo of the {}.', 
    'a muted photo of the {}.', 
    'a colorful shot of the {}.', 
    'a fresh photo of the {}.',
    'a vibrant photo of the {}.', 
    'a vintage-inspired photo of the {}.', 
    'a modern-day photo of the {}.', 
    'a bright photo of the {}.',
    'a dull photo of the {}.', 
    'a eye-catching photo of the {}.', 
    'a motion-blurred photo of the {}.', 
    'a perfectly sharp photo of the {}.',
    'a high-angle photo of the {}.', 
    'a low-angle photo of the {}.', 
    'a candid moment photo of the {}.', 
    'a momentous photo of the {}.',
    'a well-lit portrait of the {}.', 
    'a poorly lit portrait of the {}.', 
    'a finely detailed photo of the {}.', 
    'a distorted photo of the {}.',
    'a sharp-edged photo of the {}.', 
    'a soft-edged photo of the {}.', 
    'a perfect shot of the {}.', 
    'a messy photo of the {}.',
    'a crystal-clear photo of the {}.', 
    'a overexposed shot of the {}.', 
    'a blurred background photo of the {}.', 
    'a clear background photo of the {}.',
    'a dark-toned photo of the {}.', 
    'a soft-focus photo of the {}.', 
    'a well-lit indoor photo of the {}.',
    'a shadowy indoor photo of the {}.',
    'a quiet photo of the {}.', 
    'a bustling photo of the {}.', 
    'a chaotic urban photo of the {}.',
    'a vintage photograph of the {}.', 
    'a professional shot of the {}.', 
    'a artistic shot of the {}.', 
    'a striking photo of the {}.',
    'a photo of a small {}.',
    'a photo of a big {}.',
    'a photo of the {}.',
    'a blurry photo of the {}.',
    'a black and white photo of the {}.',
    'a low contrast photo of the {}.',
    'a high contrast photo of the {}.',
    'a bad photo of the {}.',
    'a good photo of the {}.',
    'a photo of the small {}.',
    'a photo of the big {}.',
    'a photo of a cute {}.',
    'a photo of a tall {}.',
    'a photo of a colorful {}.',
    'a photo of a messy {}.',
    'a photo of a clean {}.',
    'a photo of a sleeping {}.',
    'a photo of a moving {}.',
    'a photo of a playful {}.',
    'a photo of a sleepy {}.',
    'a photo of a happy {}.',
    'a photo of a sad {}.',
    'a photo of a quiet {}.',
    'a photo of a loud {}.',
    'a photo of a shiny {}.',
    'a photo of a dusty {}.',
    'a photo of a rainy {}.',
    'a photo of a snowy {}.',
    'a photo of a sunny {}.',
    'a photo of a cloudy {}.',
    'a photo of a foggy {}.',
    'a photo of a windy {}.',
    'a photo of a bright {}.',
    'a photo of a dark {}.',
    'a photo of a soft {}.',
    'a photo of a hard {}.',
    'a photo of a smooth {}.',
    'a photo of a rough {}.',
    'a photo of a wet {}.',
    'a photo of a dry {}.',
    'a photo of a cute little {}.',
    'a photo of a tall slender {}.',
    'a photo of a round {}.',
    'a photo of a square {}.',
    'a photo of a long {}.',
    'a photo of a short {}.',
    'a photo of a fluffy {}.',
    'a photo of a sleek {}.',
    'a photo of a shiny metal {}.',
    'a photo of a dull {}.',
    'a photo of a tiny {}.',
    'a photo of a huge {}.',
    'a photo of a tiny little {}.',
    'a photo of a giant {}.',
    'a photo of a quiet little {}.',
    'a photo of a loud colorful {}.',
    'a photo of a delicate {}.',
    'a photo of a sturdy {}.',
    'a photo of an old {}.',
    'a photo of a new {}.',
    'a photo of a warm {}.',
    'a photo of a cold {}.',
    'a photo of a frozen {}.',
    'a photo of a melting {}.',
    'a photo of a blooming {}.',
    'a photo of a wilting {}.',
    'a photo of a smiling {}.',
    'a photo of a frowning {}.',
    'a photo of a sleeping {}.',
    'a photo of a playing {}.',
    'a photo of a sitting {}.',
    'a photo of a standing {}.',
    'a photo of a running {}.',
    'a photo of a jumping {}.',
    'a photo of a walking {}.',
    'a photo of a crawling {}.',
    'a photo of a flying {}.',
    'a photo of a swimming {}.',
    'a photo of a clumsy {}.',
    'a photo of an elegant {}.',
    'a photo of a happy little {}.',
    'a photo of a sad {}.',
    'a photo of a surprised {}.',
    'a photo of an angry {}.',
    'a photo of a curious {}.',
    'a photo of a proud {}.',
    'a photo of a lonely {}.',
    'a photo of a friendly {}.',
    'a photo of an old wooden {}.',
    'a photo of a metal {}.',
    'a photo of a green {}.',
    'a photo of a red {}.',
    'a photo of a yellow {}.',
    'a photo of a purple {}.',
    'a photo of a black {}.',
    'a photo of a white {}.',
    'a photo of a brown {}.',
    'a photo of a gray {}.',
    'a photo of a blue {}.',
    'a photo of a transparent {}.',
    'a photo of a solid {}.',
    'a photo of a vivid {}.',
    'a photo of a pale {}.',
    'a photo of a smooth {}.',
    'a photo of a glossy {}.',
    'a photo of a matte {}.',
    'a photo of a rough-textured {}.',
    'a photo of a finely detailed {}.',
    'a photo of a low-resolution {}.',
    'a photo of a high-resolution {}.',
    'a photo of a blurry background {}.',
    'a photo of a sharp {}.',
    'a photo of a focused {}.',
    'a photo of a detailed {}.',
    'a photo of a simple {}.',
    'a photo of a complex {}.',
    'a photo of a minimal {}.',
    'a photo of a colorful object {}.',
    'a photo of a monochrome {}.',
    'a photo of a close-up {}.',
    'a photo of a wide-angle {}.',
    'a photo of a macro shot of {}.',
    'a photo of a panoramic {}.',
    'a photo of a distant {}.',
    'a photo of a side view {}.',
    'a photo of a front view {}.',
    'a photo of a top-down {}.',
    'a photo of a bird’s eye view of {}.',
    'a photo of a profile {}.',
    'a photo of a close-up shot of {}.',
    'a photo of a long exposure {}.',
    'a photo of a time-lapse {}.',
    'a photo of a candid {}.',
    'a photo of a staged {}.',
    'a photo of an action shot of {}.',
    'a photo of a natural {}.',
    'a photo of a posed {}.',
    'a photo of a quick snap of {}.',
    'a photo of a family {}.',
    'a photo of a group of {}.',
    'a photo of a single {}.',
    'a photo of a couple of {}.',
    'a photo of a trio of {}.',
    'a photo of a large {}.',
    'a photo of a small collection of {}.',
    'a photo of a detailed view of {}.',
    'a photo of a front-facing {}.',
    'a photo of a rear view {}.',
    'a photo of a top view of {}.',
    'a photo of a symmetrical {}.',
    'a photo of a crooked {}.',
    'a photo of a perfect {}.',
    'a photo of a distorted {}.',
    'a photo of a natural light {}.',
    'a photo of an artificial light {}.',
    'a photo of soft light {}.',
    'a photo of harsh lighting {}.',
    'a photo of sunlight shining on {}.',
    'a photo of a shadowed {}.',
    'a photo of a lighted {}.',
    'a photo of a dimly lit {}.',
    'a photo of a dark-lit {}.',
    'a photo of an illuminated {}.',
    'a photo of a flickering {}.',
    'a photo of a steady {}.',
    'a photo of a quiet {}.',
    'a photo of a busy {}.',
    'a photo of a still {}.',
    'a photo of a bustling {}.',
    'a photo of a peaceful {}.',
    'a photo of a hectic {}.',
    'a photo of a calm {}.',
    'a photo of a chaotic {}.',
    'a photo of a controlled {}.',
    'a photo of an untouched {}.',
    'a photo of a pristine {}.',
    'a photo of a messy {}.',
    'a photo of a well-kept {}.',
    'a photo of a broken {}.',
    'a photo of a fixed {}.',
    'a photo of a damaged {}.',
    'a photo of a repaired {}.',
    'a photo of a vintage {}.',
    'a photo of a modern {}.',
    'a photo of a retro {}.',
    'a photo of a futuristic {}.',
    'a photo of a classic {}.',
    'a photo of a rustic {}.',
    'a photo of a contemporary {}.',
    'a photo of a minimalist {}.',
    'a photo of an elaborate {}.',
    'a photo of a structured {}.',
    'a photo of an organic {}.',
    'a photo of a whimsical {}.',
    'a photo of a dramatic {}.',
    'a photo of a vibrant {}.',
    'a photo of a muted {}.',
    'a photo of an abstract {}.'
]

ALL_TEMPLATES = synonym_replace_templates+word_order_templates+emotional_templates+tense_variation_templates+detailed_description_templates